DELIMITER ;;

USE cygnus_rootnode;;

DROP FUNCTION IF EXISTS NC_NewContainer;;
CREATE FUNCTION NC_NewContainer()
  RETURNS INTEGER UNSIGNED
  LANGUAGE SQL
  MODIFIES SQL DATA
  SQL SECURITY INVOKER
BEGIN
  UPDATE NC_Config SET ContainerIncrement = LAST_INSERT_ID(ContainerIncrement+1);
  RETURN LAST_INSERT_ID();
END;;

