DELIMITER ;;

USE cygnus_rootnode;;

DROP PROCEDURE IF EXISTS NC_HighOrbitSetAttribute;;
CREATE PROCEDURE NC_HighOrbitSetAttribute(
    p_PLID INTEGER UNSIGNED,
    p_Owner INTEGER UNSIGNED,
    p_Item SMALLINT UNSIGNED,
    p_Amount INTEGER
  )
  LANGUAGE SQL
  MODIFIES SQL DATA
  SQL SECURITY INVOKER
BEGIN
  INSERT INTO NC_HighOrbit VALUES (p_PLID, p_Owner, p_Item, p_Amount)
    ON DUPLICATE KEY UPDATE Amount=p_Amount;
END;;

DROP PROCEDURE IF EXISTS NC_HighOrbitGetAttribute;;
CREATE PROCEDURE NC_HighOrbitGetAttribute(
    p_PLID INTEGER UNSIGNED,
    p_Owner INTEGER UNSIGNED,
    p_Item SMALLINT UNSIGNED
  )
  LANGUAGE SQL
  READS SQL DATA
  SQL SECURITY INVOKER
BEGIN
  SELECT Amount AS Result
  FROM NC_HighOrbit
  WHERE PLID=p_PLID AND Owner=p_Owner AND ItemType=p_Item;
END;;

DROP PROCEDURE IF EXISTS NC_HighOrbitGet;;
CREATE PROCEDURE NC_HighOrbitGet(
    p_PLID INTEGER UNSIGNED
  )
  LANGUAGE SQL
  READS SQL DATA
  SQL SECURITY INVOKER
BEGIN
  SELECT Owner, ItemType, Amount 
  FROM NC_HighOrbit
  WHERE PLID=p_PLID
  ORDER BY Owner;
END;;

