DELIMITER ;;

USE cygnus_rootnode;;

DROP PROCEDURE IF EXISTS NC_LowOrbitSetAttribute;;
CREATE PROCEDURE NC_LowOrbitSetAttribute(
    p_PLID INTEGER UNSIGNED,
    p_Item SMALLINT UNSIGNED,
    p_Value INTEGER
  )
  LANGUAGE SQL
  MODIFIES SQL DATA
  SQL SECURITY INVOKER
BEGIN
  INSERT INTO NC_LowOrbit VALUES (p_PLID, p_Item, p_Value)
    ON DUPLICATE KEY UPDATE Amount=p_Value;
END;;

DROP PROCEDURE IF EXISTS NC_LowOrbitGetAttribute;;
CREATE PROCEDURE NC_LowOrbitGetAttribute(
    p_PLID INTEGER UNSIGNED,
    p_Item SMALLINT UNSIGNED
  )
  LANGUAGE SQL
  READS SQL DATA
  SQL SECURITY INVOKER
BEGIN
  SELECT Amount AS Result
  FROM NC_LowOrbit
  WHERE PLID=p_PLID AND ItemType=p_Item;
END;;

DROP PROCEDURE IF EXISTS NC_LowOrbitGet;;
CREATE PROCEDURE NC_LowOrbitGet(
    p_PLID INTEGER UNSIGNED
  )
  LANGUAGE SQL
  READS SQL DATA
  SQL SECURITY INVOKER
BEGIN
  SELECT ItemType, Amount 
  FROM NC_LowOrbit
  WHERE PLID=p_PLID;
END;;

