DELIMITER ;;

USE cygnus_rootnode;;

DROP PROCEDURE IF EXISTS NC_PlayerCreate;;
CREATE PROCEDURE NC_PlayerCreate(
    p_account INTEGER UNSIGNED,
    p_time INTEGER UNSIGNED,
    p_X SMALLINT,
    p_Y SMALLINT
  )
  LANGUAGE SQL
  MODIFIES SQL DATA
  SQL SECURITY INVOKER
BEGIN
  DECLARE Result INTEGER UNSIGNED;
  INSERT INTO NC_Player(`AID`,`LastUpdate`,`HomeX`,`HomeY`) VALUES (p_account, p_time, p_X, p_Y);
  SELECT LAST_INSERT_ID() INTO Result;
  UPDATE NC_Account SET `PID`=Result WHERE `AID`=p_account;
  SELECT Result AS `Result`;
END;;

DROP PROCEDURE IF EXISTS NC_AID_to_PID;;
CREATE PROCEDURE NC_AID_to_PID(
    p_AID INTEGER UNSIGNED
    )
  LANGUAGE SQL
  READS SQL DATA
  SQL SECURITY INVOKER
BEGIN
  SELECT PID FROM NC_Player WHERE AID=p_AID;
END;;

DROP PROCEDURE IF EXISTS NC_PlayerHome;;
CREATE PROCEDURE NC_PlayerHome(
    p_PID INTEGER UNSIGNED
    )
  LANGUAGE SQL
  READS SQL DATA
  SQL SECURITY INVOKER
BEGIN
  SELECT HomeX, HomeY FROM NC_Player WHERE PID=p_PID;
END;;

